### ISSUE TITLE
[Feature request] Add tslint

### ISSUE THREAD

**Issue by iscekic** [cafreeman/generator-mobx-react#3]
ES6 has eslint, TS should have tslint. :smile:

**Comment by cafreeman** [comment]
:) Do you know of any good rule presets or anything for TSlint? If you can can provide a sane default, I'd be happy to add it and start there.

**Comment by iscekic** [comment]
https://github.com/Microsoft/tslint-microsoft-contrib maybe? :)

**Comment by cafreeman** [comment]
@Torwori Just added TSLint and a _really_ basic config to get people started. It turns out that both `tslint:recommended` and the microsoft preset that you linked are pretty strongly opinionated and I didn't want to freak anyone out by throwing up tslint errors all over the place.

The goal for now is that the pieces are there, and users will hopefully see the config file and have an easy time extending from there.

**Comment by iscekic** [comment]
Sounds good!
